# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Crack the Code
tagline:          Crack the Code - A conference for women in progressive data analytics and technology
description:      'A conference for women in progressive data, analytics, and technology'
url:              http://crackthecode.io
baseurl:          /

author:
  name:           'Data Suffragettes'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.1

#github:
#  repo:           https://github.com/poole/hyde
